// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package db

import (
	"context"
	"database/sql"
)

const countAPIKeys = `-- name: CountAPIKeys :one
SELECT count(*) FROM api_keys
`

func (q *Queries) CountAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAPIKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (admin_id, name, prefix, hash, scope, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, admin_id, name, prefix, hash, scope, created_at, expires_at, last_used_at, last_ip
`

type CreateAPIKeyParams struct {
	AdminID   int64
	Name      string
	Prefix    string
	Hash      string
	Scope     string
	CreatedAt int64
	ExpiresAt sql.NullInt64
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.AdminID,
		arg.Name,
		arg.Prefix,
		arg.Hash,
		arg.Scope,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.Scope,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastIp,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAPIKeysOf = `-- name: DeleteAPIKeysOf :execrows
DELETE FROM api_keys WHERE admin_id = ?
`

func (q *Queries) DeleteAPIKeysOf(ctx context.Context, adminID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIKeysOf, adminID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, admin_id, name, prefix, hash, scope, created_at, expires_at, last_used_at, last_ip FROM api_keys WHERE hash = ?
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, hash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, hash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.Scope,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastIp,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, admin_id, name, prefix, hash, scope, created_at, expires_at, last_used_at, last_ip FROM api_keys ORDER BY id
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.Scope,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = ?, last_ip = ?
WHERE id = ? AND (last_used_at IS NULL OR last_used_at < ?)
`

type TouchAPIKeyParams struct {
	LastUsedAt   sql.NullInt64
	LastIp       string
	ID           int64
	LastUsedAt_2 sql.NullInt64
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIKey,
		arg.LastUsedAt,
		arg.LastIp,
		arg.ID,
		arg.LastUsedAt_2,
	)
	return err
}
