// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"database/sql"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admins
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (username, password_hash, created_at) VALUES (?, ?, ?)
RETURNING id, username, password_hash, totp_secret, recovery_codes, created_at, last_login_at
`

type CreateAdminParams struct {
	Username     string
	PasswordHash string
	CreatedAt    int64
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createAdmin, arg.Username, arg.PasswordHash, arg.CreatedAt)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.RecoveryCodes,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id_hash, admin_id, csrf_token, created_at, last_seen_at, expires_at, ip, user_agent)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	IDHash     string
	AdminID    int64
	CsrfToken  string
	CreatedAt  int64
	LastSeenAt int64
	ExpiresAt  int64
	Ip         string
	UserAgent  string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.IDHash,
		arg.AdminID,
		arg.CsrfToken,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const deleteAdminSessions = `-- name: DeleteAdminSessions :exec
DELETE FROM sessions WHERE admin_id = ?
`

func (q *Queries) DeleteAdminSessions(ctx context.Context, adminID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAdminSessions, adminID)
	return err
}

const deleteAdminSessionsExcept = `-- name: DeleteAdminSessionsExcept :exec
DELETE FROM sessions WHERE admin_id = ? AND id_hash <> ?
`

type DeleteAdminSessionsExceptParams struct {
	AdminID int64
	IDHash  string
}

func (q *Queries) DeleteAdminSessionsExcept(ctx context.Context, arg DeleteAdminSessionsExceptParams) error {
	_, err := q.db.ExecContext(ctx, deleteAdminSessionsExcept, arg.AdminID, arg.IDHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, idHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, idHash)
	return err
}

const deleteStaleSessions = `-- name: DeleteStaleSessions :exec
DELETE FROM sessions WHERE expires_at < ?1 OR last_seen_at < ?2
`

type DeleteStaleSessionsParams struct {
	Now        int64
	IdleBefore int64
}

func (q *Queries) DeleteStaleSessions(ctx context.Context, arg DeleteStaleSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteStaleSessions, arg.Now, arg.IdleBefore)
	return err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, username, password_hash, totp_secret, recovery_codes, created_at, last_login_at FROM admins WHERE id = ?
`

func (q *Queries) GetAdmin(ctx context.Context, id int64) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdmin, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.RecoveryCodes,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, totp_secret, recovery_codes, created_at, last_login_at FROM admins WHERE username = ?
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.RecoveryCodes,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id_hash, admin_id, csrf_token, created_at, last_seen_at, expires_at, ip, user_agent FROM sessions WHERE id_hash = ?
`

func (q *Queries) GetSession(ctx context.Context, idHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, idHash)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.AdminID,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (ts, admin_id, action, target_type, target_id, ip, details)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditParams struct {
	Ts         int64
	AdminID    sql.NullInt64
	Action     string
	TargetType sql.NullString
	TargetID   sql.NullString
	Ip         sql.NullString
	Details    sql.NullString
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.Ts,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Ip,
		arg.Details,
	)
	return err
}

const listAdminSessions = `-- name: ListAdminSessions :many
SELECT id_hash, admin_id, csrf_token, created_at, last_seen_at, expires_at, ip, user_agent FROM sessions WHERE admin_id = ? ORDER BY last_seen_at DESC
`

func (q *Queries) ListAdminSessions(ctx context.Context, adminID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listAdminSessions, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.IDHash,
			&i.AdminID,
			&i.CsrfToken,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.Ip,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, password_hash, totp_secret, recovery_codes, created_at, last_login_at FROM admins ORDER BY id
`

func (q *Queries) ListAdmins(ctx context.Context) ([]Admin, error) {
	rows, err := q.db.QueryContext(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Admin{}
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.TotpSecret,
			&i.RecoveryCodes,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudit = `-- name: ListAudit :many
SELECT id, ts, admin_id, "action", target_type, target_id, ip, details FROM audit_log WHERE id < ?1 ORDER BY id DESC LIMIT ?2
`

type ListAuditParams struct {
	BeforeID int64
	Lim      int64
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, arg.BeforeID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Ip,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAudit = `-- name: PruneAudit :execrows
DELETE FROM audit_log WHERE ts < ?
`

func (q *Queries) PruneAudit(ctx context.Context, ts int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneAudit, ts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAdminLastLogin = `-- name: SetAdminLastLogin :exec
UPDATE admins SET last_login_at = ? WHERE id = ?
`

type SetAdminLastLoginParams struct {
	LastLoginAt sql.NullInt64
	ID          int64
}

func (q *Queries) SetAdminLastLogin(ctx context.Context, arg SetAdminLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, setAdminLastLogin, arg.LastLoginAt, arg.ID)
	return err
}

const setAdminPassword = `-- name: SetAdminPassword :exec
UPDATE admins SET password_hash = ? WHERE id = ?
`

type SetAdminPasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) SetAdminPassword(ctx context.Context, arg SetAdminPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setAdminPassword, arg.PasswordHash, arg.ID)
	return err
}

const setAdminTOTP = `-- name: SetAdminTOTP :exec
UPDATE admins SET totp_secret = ?, recovery_codes = ? WHERE id = ?
`

type SetAdminTOTPParams struct {
	TotpSecret    sql.NullString
	RecoveryCodes sql.NullString
	ID            int64
}

func (q *Queries) SetAdminTOTP(ctx context.Context, arg SetAdminTOTPParams) error {
	_, err := q.db.ExecContext(ctx, setAdminTOTP, arg.TotpSecret, arg.RecoveryCodes, arg.ID)
	return err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type SetSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const spendAdminRecoveryCodes = `-- name: SpendAdminRecoveryCodes :execrows
UPDATE admins SET recovery_codes = ?1 WHERE id = ?2 AND recovery_codes = ?3
`

type SpendAdminRecoveryCodesParams struct {
	Rest sql.NullString
	ID   int64
	Was  sql.NullString
}

// Takes a recovery code out of the list it was found in: 0 rows means another login spent
// a code from the same list first, and this one is refused.
func (q *Queries) SpendAdminRecoveryCodes(ctx context.Context, arg SpendAdminRecoveryCodesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, spendAdminRecoveryCodes, arg.Rest, arg.ID, arg.Was)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = ? WHERE id_hash = ?
`

type TouchSessionParams struct {
	LastSeenAt int64
	IDHash     string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.IDHash)
	return err
}
