// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: autotune.sql

package db

import (
	"context"
)

const addInboundEvent = `-- name: AddInboundEvent :exec
INSERT INTO inbound_events (inbound_id, node_id, kind, network, old_value, new_value, reason, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type AddInboundEventParams struct {
	InboundID int64
	NodeID    int64
	Kind      string
	Network   string
	OldValue  string
	NewValue  string
	Reason    string
	CreatedAt int64
}

func (q *Queries) AddInboundEvent(ctx context.Context, arg AddInboundEventParams) error {
	_, err := q.db.ExecContext(ctx, addInboundEvent,
		arg.InboundID,
		arg.NodeID,
		arg.Kind,
		arg.Network,
		arg.OldValue,
		arg.NewValue,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const lastInboundEvents = `-- name: LastInboundEvents :many
SELECT id, inbound_id, node_id, kind, network, old_value, new_value, reason, created_at FROM inbound_events WHERE id IN (SELECT MAX(id) FROM inbound_events GROUP BY inbound_id)
`

// The latest automatic change of every inbound that had one.
func (q *Queries) LastInboundEvents(ctx context.Context) ([]InboundEvent, error) {
	rows, err := q.db.QueryContext(ctx, lastInboundEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboundEvent{}
	for rows.Next() {
		var i InboundEvent
		if err := rows.Scan(
			&i.ID,
			&i.InboundID,
			&i.NodeID,
			&i.Kind,
			&i.Network,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboundEventsSince = `-- name: ListInboundEventsSince :many
SELECT id, inbound_id, node_id, kind, network, old_value, new_value, reason, created_at FROM inbound_events WHERE created_at >= ? ORDER BY id
`

func (q *Queries) ListInboundEventsSince(ctx context.Context, createdAt int64) ([]InboundEvent, error) {
	rows, err := q.db.QueryContext(ctx, listInboundEventsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboundEvent{}
	for rows.Next() {
		var i InboundEvent
		if err := rows.Scan(
			&i.ID,
			&i.InboundID,
			&i.NodeID,
			&i.Kind,
			&i.Network,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboundReachSince = `-- name: ListInboundReachSince :many
SELECT slot, inbound_id, at FROM inbound_reach WHERE at >= ?
`

func (q *Queries) ListInboundReachSince(ctx context.Context, at int64) ([]InboundReach, error) {
	rows, err := q.db.QueryContext(ctx, listInboundReachSince, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboundReach{}
	for rows.Next() {
		var i InboundReach
		if err := rows.Scan(&i.Slot, &i.InboundID, &i.At); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubFetchesSince = `-- name: ListSubFetchesSince :many
SELECT user_id, ip, fetched_at FROM sub_fetches WHERE fetched_at >= ?
`

func (q *Queries) ListSubFetchesSince(ctx context.Context, fetchedAt int64) ([]SubFetch, error) {
	rows, err := q.db.QueryContext(ctx, listSubFetchesSince, fetchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubFetch{}
	for rows.Next() {
		var i SubFetch
		if err := rows.Scan(&i.UserID, &i.Ip, &i.FetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneInboundEvents = `-- name: PruneInboundEvents :exec
DELETE FROM inbound_events WHERE created_at < ?
`

func (q *Queries) PruneInboundEvents(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneInboundEvents, createdAt)
	return err
}

const pruneInboundReach = `-- name: PruneInboundReach :exec
DELETE FROM inbound_reach WHERE at < ?
`

func (q *Queries) PruneInboundReach(ctx context.Context, at int64) error {
	_, err := q.db.ExecContext(ctx, pruneInboundReach, at)
	return err
}

const pruneSubFetches = `-- name: PruneSubFetches :exec
DELETE FROM sub_fetches WHERE fetched_at < ?
`

func (q *Queries) PruneSubFetches(ctx context.Context, fetchedAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneSubFetches, fetchedAt)
	return err
}

const recordSubFetch = `-- name: RecordSubFetch :exec
INSERT INTO sub_fetches (user_id, ip, fetched_at) VALUES (?, ?, ?)
ON CONFLICT (user_id, ip) DO UPDATE SET fetched_at = excluded.fetched_at
`

type RecordSubFetchParams struct {
	UserID    int64
	Ip        string
	FetchedAt int64
}

func (q *Queries) RecordSubFetch(ctx context.Context, arg RecordSubFetchParams) error {
	_, err := q.db.ExecContext(ctx, recordSubFetch, arg.UserID, arg.Ip, arg.FetchedAt)
	return err
}

const setInboundAuto = `-- name: SetInboundAuto :exec
UPDATE inbounds SET auto_port = ?, auto_sni = ? WHERE id = ?
`

type SetInboundAutoParams struct {
	AutoPort int64
	AutoSni  int64
	ID       int64
}

// The switches do not change what clients get, so updated_at stays.
func (q *Queries) SetInboundAuto(ctx context.Context, arg SetInboundAutoParams) error {
	_, err := q.db.ExecContext(ctx, setInboundAuto, arg.AutoPort, arg.AutoSni, arg.ID)
	return err
}

const setInboundListen = `-- name: SetInboundListen :exec
UPDATE inbounds SET listen = ? WHERE id = ?
`

type SetInboundListenParams struct {
	Listen string
	ID     int64
}

// The listen address is the node's business, clients get nothing new: updated_at stays.
func (q *Queries) SetInboundListen(ctx context.Context, arg SetInboundListenParams) error {
	_, err := q.db.ExecContext(ctx, setInboundListen, arg.Listen, arg.ID)
	return err
}

const upsertInboundReach = `-- name: UpsertInboundReach :exec
INSERT INTO inbound_reach (slot, inbound_id, at) VALUES (?, ?, ?)
ON CONFLICT (slot, inbound_id) DO UPDATE SET at = max(at, excluded.at)
`

type UpsertInboundReachParams struct {
	Slot      string
	InboundID int64
	At        int64
}

func (q *Queries) UpsertInboundReach(ctx context.Context, arg UpsertInboundReachParams) error {
	_, err := q.db.ExecContext(ctx, upsertInboundReach, arg.Slot, arg.InboundID, arg.At)
	return err
}
