// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cascade.sql

package db

import (
	"context"
	"database/sql"
)

const addRelayUser = `-- name: AddRelayUser :exec
INSERT INTO relay_users (exit_node_id, src_node_id, uuid) VALUES (?, ?, ?)
ON CONFLICT (exit_node_id, src_node_id) DO NOTHING
`

type AddRelayUserParams struct {
	ExitNodeID int64
	SrcNodeID  int64
	Uuid       string
}

func (q *Queries) AddRelayUser(ctx context.Context, arg AddRelayUserParams) error {
	_, err := q.db.ExecContext(ctx, addRelayUser, arg.ExitNodeID, arg.SrcNodeID, arg.Uuid)
	return err
}

const createNodeRelay = `-- name: CreateNodeRelay :one
INSERT INTO node_relays (node_id, port, config, created_at) VALUES (?, ?, ?, ?)
ON CONFLICT (node_id) DO UPDATE SET node_id = excluded.node_id
RETURNING node_id, port, config, outbound, exit_node_id, created_at
`

type CreateNodeRelayParams struct {
	NodeID    int64
	Port      string
	Config    string
	CreatedAt int64
}

func (q *Queries) CreateNodeRelay(ctx context.Context, arg CreateNodeRelayParams) (NodeRelay, error) {
	row := q.db.QueryRowContext(ctx, createNodeRelay,
		arg.NodeID,
		arg.Port,
		arg.Config,
		arg.CreatedAt,
	)
	var i NodeRelay
	err := row.Scan(
		&i.NodeID,
		&i.Port,
		&i.Config,
		&i.Outbound,
		&i.ExitNodeID,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeRelay = `-- name: GetNodeRelay :one
SELECT node_id, port, config, outbound, exit_node_id, created_at FROM node_relays WHERE node_id = ?
`

func (q *Queries) GetNodeRelay(ctx context.Context, nodeID int64) (NodeRelay, error) {
	row := q.db.QueryRowContext(ctx, getNodeRelay, nodeID)
	var i NodeRelay
	err := row.Scan(
		&i.NodeID,
		&i.Port,
		&i.Config,
		&i.Outbound,
		&i.ExitNodeID,
		&i.CreatedAt,
	)
	return i, err
}

const getRelayUser = `-- name: GetRelayUser :one
SELECT uuid FROM relay_users WHERE exit_node_id = ? AND src_node_id = ?
`

type GetRelayUserParams struct {
	ExitNodeID int64
	SrcNodeID  int64
}

func (q *Queries) GetRelayUser(ctx context.Context, arg GetRelayUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getRelayUser, arg.ExitNodeID, arg.SrcNodeID)
	var uuid string
	err := row.Scan(&uuid)
	return uuid, err
}

const listNodeRelays = `-- name: ListNodeRelays :many
SELECT node_id, port, config, outbound, exit_node_id, created_at FROM node_relays ORDER BY node_id
`

func (q *Queries) ListNodeRelays(ctx context.Context) ([]NodeRelay, error) {
	rows, err := q.db.QueryContext(ctx, listNodeRelays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeRelay{}
	for rows.Next() {
		var i NodeRelay
		if err := rows.Scan(
			&i.NodeID,
			&i.Port,
			&i.Config,
			&i.Outbound,
			&i.ExitNodeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelayUsers = `-- name: ListRelayUsers :many
SELECT exit_node_id, src_node_id, uuid FROM relay_users WHERE exit_node_id = ? ORDER BY src_node_id
`

func (q *Queries) ListRelayUsers(ctx context.Context, exitNodeID int64) ([]RelayUser, error) {
	rows, err := q.db.QueryContext(ctx, listRelayUsers, exitNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RelayUser{}
	for rows.Next() {
		var i RelayUser
		if err := rows.Scan(&i.ExitNodeID, &i.SrcNodeID, &i.Uuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInboundExit = `-- name: SetInboundExit :exec
UPDATE inbounds SET exit_node_id = ?, outbound = ? WHERE id = ?
`

type SetInboundExitParams struct {
	ExitNodeID sql.NullInt64
	Outbound   string
	ID         int64
}

func (q *Queries) SetInboundExit(ctx context.Context, arg SetInboundExitParams) error {
	_, err := q.db.ExecContext(ctx, setInboundExit, arg.ExitNodeID, arg.Outbound, arg.ID)
	return err
}

const setNodeRelayRoute = `-- name: SetNodeRelayRoute :exec
UPDATE node_relays SET outbound = ?, exit_node_id = ? WHERE node_id = ?
`

type SetNodeRelayRouteParams struct {
	Outbound   string
	ExitNodeID sql.NullInt64
	NodeID     int64
}

func (q *Queries) SetNodeRelayRoute(ctx context.Context, arg SetNodeRelayRouteParams) error {
	_, err := q.db.ExecContext(ctx, setNodeRelayRoute, arg.Outbound, arg.ExitNodeID, arg.NodeID)
	return err
}
