// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"
	"database/sql"
)

const countBoundDevices = `-- name: CountBoundDevices :one
SELECT count(*) FROM bound_devices WHERE user_id = ?
`

func (q *Queries) CountBoundDevices(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBoundDevices, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBoundDevice = `-- name: CreateBoundDevice :one
INSERT INTO bound_devices (user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen
`

type CreateBoundDeviceParams struct {
	UserID    int64
	Hwid      string
	SlotID    int64
	Os        string
	OsVersion string
	Model     string
	App       string
	LastIp    string
	CreatedAt int64
	LastSeen  int64
}

func (q *Queries) CreateBoundDevice(ctx context.Context, arg CreateBoundDeviceParams) (BoundDevice, error) {
	row := q.db.QueryRowContext(ctx, createBoundDevice,
		arg.UserID,
		arg.Hwid,
		arg.SlotID,
		arg.Os,
		arg.OsVersion,
		arg.Model,
		arg.App,
		arg.LastIp,
		arg.CreatedAt,
		arg.LastSeen,
	)
	var i BoundDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hwid,
		&i.SlotID,
		&i.Os,
		&i.OsVersion,
		&i.Model,
		&i.App,
		&i.LastIp,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const deleteBoundDevice = `-- name: DeleteBoundDevice :exec
DELETE FROM bound_devices WHERE id = ?
`

func (q *Queries) DeleteBoundDevice(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBoundDevice, id)
	return err
}

const deleteBoundDevicesOf = `-- name: DeleteBoundDevicesOf :exec
DELETE FROM bound_devices WHERE user_id = ?
`

func (q *Queries) DeleteBoundDevicesOf(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBoundDevicesOf, userID)
	return err
}

const getBoundDevice = `-- name: GetBoundDevice :one
SELECT id, user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen FROM bound_devices WHERE user_id = ? AND hwid = ?
`

type GetBoundDeviceParams struct {
	UserID int64
	Hwid   string
}

func (q *Queries) GetBoundDevice(ctx context.Context, arg GetBoundDeviceParams) (BoundDevice, error) {
	row := q.db.QueryRowContext(ctx, getBoundDevice, arg.UserID, arg.Hwid)
	var i BoundDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hwid,
		&i.SlotID,
		&i.Os,
		&i.OsVersion,
		&i.Model,
		&i.App,
		&i.LastIp,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getBoundDeviceByID = `-- name: GetBoundDeviceByID :one
SELECT id, user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen FROM bound_devices WHERE id = ? AND user_id = ?
`

type GetBoundDeviceByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetBoundDeviceByID(ctx context.Context, arg GetBoundDeviceByIDParams) (BoundDevice, error) {
	row := q.db.QueryRowContext(ctx, getBoundDeviceByID, arg.ID, arg.UserID)
	var i BoundDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hwid,
		&i.SlotID,
		&i.Os,
		&i.OsVersion,
		&i.Model,
		&i.App,
		&i.LastIp,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const listBoundDevices = `-- name: ListBoundDevices :many
SELECT id, user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen FROM bound_devices WHERE user_id = ? ORDER BY created_at, id
`

func (q *Queries) ListBoundDevices(ctx context.Context, userID int64) ([]BoundDevice, error) {
	rows, err := q.db.QueryContext(ctx, listBoundDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoundDevice{}
	for rows.Next() {
		var i BoundDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hwid,
			&i.SlotID,
			&i.Os,
			&i.OsVersion,
			&i.Model,
			&i.App,
			&i.LastIp,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceSlots = `-- name: ListDeviceSlots :many
SELECT s.name AS slot_name, d.user_id, d.last_seen FROM bound_devices d JOIN slots s ON s.id = d.slot_id WHERE d.hwid != ''
`

type ListDeviceSlotsRow struct {
	SlotName string
	UserID   int64
	LastSeen int64
}

// Slots of bound devices with an id: keys of their own, profile fetches of their own.
func (q *Queries) ListDeviceSlots(ctx context.Context) ([]ListDeviceSlotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceSlotsRow{}
	for rows.Next() {
		var i ListDeviceSlotsRow
		if err := rows.Scan(&i.SlotName, &i.UserID, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdleBoundDevices = `-- name: ListIdleBoundDevices :many
SELECT id, user_id, hwid, slot_id, os, os_version, model, app, last_ip, created_at, last_seen FROM bound_devices WHERE last_seen < ?
`

func (q *Queries) ListIdleBoundDevices(ctx context.Context, lastSeen int64) ([]BoundDevice, error) {
	rows, err := q.db.QueryContext(ctx, listIdleBoundDevices, lastSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoundDevice{}
	for rows.Next() {
		var i BoundDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hwid,
			&i.SlotID,
			&i.Os,
			&i.OsVersion,
			&i.Model,
			&i.App,
			&i.LastIp,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserSlot = `-- name: SetUserSlot :exec
UPDATE users SET slot_id = ?, updated_at = ? WHERE id = ?
`

type SetUserSlotParams struct {
	SlotID    sql.NullInt64
	UpdatedAt int64
	ID        int64
}

// A new own slot for the user, same subscription link (the shared device was unbound).
func (q *Queries) SetUserSlot(ctx context.Context, arg SetUserSlotParams) error {
	_, err := q.db.ExecContext(ctx, setUserSlot, arg.SlotID, arg.UpdatedAt, arg.ID)
	return err
}

const setUserUnboundAt = `-- name: SetUserUnboundAt :exec
UPDATE users SET unbound_at = ? WHERE id = ?
`

type SetUserUnboundAtParams struct {
	UnboundAt int64
	ID        int64
}

func (q *Queries) SetUserUnboundAt(ctx context.Context, arg SetUserUnboundAtParams) error {
	_, err := q.db.ExecContext(ctx, setUserUnboundAt, arg.UnboundAt, arg.ID)
	return err
}

const touchBoundDevice = `-- name: TouchBoundDevice :exec
UPDATE bound_devices SET os = ?, os_version = ?, model = ?, app = ?, last_ip = ?, last_seen = ? WHERE id = ?
`

type TouchBoundDeviceParams struct {
	Os        string
	OsVersion string
	Model     string
	App       string
	LastIp    string
	LastSeen  int64
	ID        int64
}

func (q *Queries) TouchBoundDevice(ctx context.Context, arg TouchBoundDeviceParams) error {
	_, err := q.db.ExecContext(ctx, touchBoundDevice,
		arg.Os,
		arg.OsVersion,
		arg.Model,
		arg.App,
		arg.LastIp,
		arg.LastSeen,
		arg.ID,
	)
	return err
}
