// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Admin struct {
	ID            int64
	Username      string
	PasswordHash  string
	TotpSecret    sql.NullString
	RecoveryCodes sql.NullString
	CreatedAt     int64
	LastLoginAt   sql.NullInt64
}

type ApiKey struct {
	ID         int64
	AdminID    int64
	Name       string
	Prefix     string
	Hash       string
	Scope      string
	CreatedAt  int64
	ExpiresAt  sql.NullInt64
	LastUsedAt sql.NullInt64
	LastIp     string
}

type AuditLog struct {
	ID         int64
	Ts         int64
	AdminID    sql.NullInt64
	Action     string
	TargetType sql.NullString
	TargetID   sql.NullString
	Ip         sql.NullString
	Details    sql.NullString
}

type BoundDevice struct {
	ID        int64
	UserID    int64
	Hwid      string
	SlotID    int64
	Os        string
	OsVersion string
	Model     string
	App       string
	LastIp    string
	CreatedAt int64
	LastSeen  int64
}

type Device struct {
	UserID    int64
	Ip        string
	FirstSeen int64
	LastSeen  int64
}

type Inbound struct {
	ID          int64
	NodeID      int64
	Name        string
	Preset      string
	Port        string
	Enabled     int64
	Settings    string
	CreatedAt   int64
	UpdatedAt   int64
	DisplayName string
	Config      string
	AutoPort    int64
	AutoSni     int64
	Outbound    string
	ExitNodeID  sql.NullInt64
	PoolID      sql.NullInt64
	Listen      string
}

type InboundEvent struct {
	ID        int64
	InboundID int64
	NodeID    int64
	Kind      string
	Network   string
	OldValue  string
	NewValue  string
	Reason    string
	CreatedAt int64
}

type InboundReach struct {
	Slot      string
	InboundID int64
	At        int64
}

type Node struct {
	ID         int64
	Name       string
	Address    string
	PublicHost string
	Domain     string
	CertSha256 string
	Enabled    int64
	CreatedAt  int64
	UpdatedAt  int64
}

type NodeRelay struct {
	NodeID     int64
	Port       string
	Config     string
	Outbound   string
	ExitNodeID sql.NullInt64
	CreatedAt  int64
}

type NodeState struct {
	Key   string
	Value string
}

type NodeWarp struct {
	NodeID        int64
	Enabled       int64
	Source        string
	PrivateKey    string
	PeerPublicKey string
	Endpoint      string
	Ipv4          string
	Ipv6          string
	Reserved      string
	Mtu           int64
	AccountID     string
	AccountToken  string
	Plus          int64
	Routes        string
	CreatedAt     int64
	UpdatedAt     int64
}

type NodeUpstreamRelay struct {
	NodeID      int64
	Enabled     int64
	Protocol    string
	Server      string
	Port        int64
	Uuid        string
	Flow        string
	Tls         int64
	Sni         string
	PublicKey   string
	ShortID     string
	SpiderX     string
	Fingerprint string
	Inbounds    string
	CreatedAt   int64
	UpdatedAt   int64
}

type Payment struct {
	ID         int64
	Provider   string
	Payload    string
	ExternalID sql.NullString
	TgID       int64
	Kind       string
	UserID     sql.NullInt64
	TariffID   sql.NullInt64
	PackageID  sql.NullInt64
	TariffName string
	Amount     int64
	Currency   string
	Status     string
	Error      string
	PayUrl     string
	CreatedAt  int64
	PaidAt     sql.NullInt64
	AppliedAt  sql.NullInt64
	RefundedAt sql.NullInt64
}

type RelayUser struct {
	ExitNodeID int64
	SrcNodeID  int64
	Uuid       string
}

type Session struct {
	IDHash     string
	AdminID    int64
	CsrfToken  string
	CreatedAt  int64
	LastSeenAt int64
	ExpiresAt  int64
	Ip         string
	UserAgent  string
}

type Setting struct {
	Key   string
	Value string
}

type Slot struct {
	ID        int64
	Name      string
	Uuid      string
	Secret    string
	State     string
	CreatedAt int64
	BurnedAt  sql.NullInt64
}

type SlotCounter struct {
	ID   int64
	Last int64
}

type SubFetch struct {
	UserID    int64
	Ip        string
	FetchedAt int64
}

type Tariff struct {
	ID            int64
	Name          string
	TrafficLimit  sql.NullInt64
	DurationDays  int64
	DeviceLimit   sql.NullInt64
	ResetStrategy string
	PriceLabel    string
	Sort          int64
	Archived      int64
	CreatedAt     int64
	BillingDay    sql.NullInt64
	PriceStars    sql.NullInt64
	PriceRub      sql.NullInt64
	OnSale        int64
}

type TariffPool struct {
	TariffID     int64
	PoolID       int64
	TrafficLimit int64
}

type TgChat struct {
	TgID      int64
	Username  string
	FirstName string
	MenuMsgID int64
	Current   int64
	Blocked   int64
	CreatedAt int64
	UpdatedAt int64
}

type TgLink struct {
	UserID    int64
	TgID      int64
	CreatedAt int64
}

type TgNotice struct {
	UserID int64
	Kind   string
	Period int64
	SentAt int64
}

type TrafficDaily struct {
	UserID int64
	Day    int64
	Up     int64
	Down   int64
}

type TrafficGrant struct {
	ID        int64
	UserID    int64
	PoolID    sql.NullInt64
	Bytes     int64
	Remaining int64
	Lifetime  string
	ExpiresAt sql.NullInt64
	Source    string
	PaymentID sql.NullInt64
	PackageID sql.NullInt64
	Note      string
	CreatedAt int64
}

type TrafficHourly struct {
	UserID int64
	Hour   int64
	Up     int64
	Down   int64
}

type TrafficPackage struct {
	ID         int64
	Name       string
	Bytes      int64
	PoolID     sql.NullInt64
	Lifetime   string
	Days       int64
	PriceStars sql.NullInt64
	PriceRub   sql.NullInt64
	OnSale     int64
	Sort       int64
	Archived   int64
	CreatedAt  int64
}

type TrafficPool struct {
	ID        int64
	Name      string
	CreatedAt int64
}

type User struct {
	ID            int64
	Name          string
	Contact       string
	Note          string
	Tags          string
	Status        string
	TariffID      sql.NullInt64
	TrafficLimit  sql.NullInt64
	DeviceLimit   sql.NullInt64
	ResetStrategy string
	PeriodDays    int64
	PeriodStart   int64
	UsedUp        int64
	UsedDown      int64
	TotalUp       int64
	TotalDown     int64
	ExpiresAt     sql.NullInt64
	Inbounds      sql.NullString
	SubToken      string
	SlotID        sql.NullInt64
	OnlineAt      sql.NullInt64
	CreatedAt     int64
	UpdatedAt     int64
	BillingDay    sql.NullInt64
	UnboundAt     int64
}

type UserPool struct {
	UserID       int64
	PoolID       int64
	TrafficLimit sql.NullInt64
	UsedUp       int64
	UsedDown     int64
}

type TgReferral struct {
	ID           int64
	ReferrerTgID int64
	RefereeTgID  int64
	BonusApplied int64
	RewardDays   int64
	CreatedAt    int64
	AppliedAt    int64
}
