// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package db

import (
	"context"
	"database/sql"
)

const archiveTrafficPackage = `-- name: ArchiveTrafficPackage :execrows
UPDATE traffic_packages SET archived = 1, on_sale = 0 WHERE id = ? AND archived = 0
`

func (q *Queries) ArchiveTrafficPackage(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveTrafficPackage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createPackagePayment = `-- name: CreatePackagePayment :one
INSERT INTO payments (provider, payload, tg_id, kind, user_id, package_id, tariff_name, amount, currency, status, created_at)
VALUES (?, ?, ?, 'package', ?, ?, ?, ?, ?, 'pending', ?)
RETURNING id, provider, payload, external_id, tg_id, kind, user_id, tariff_id, package_id, tariff_name, amount, currency, status, error, pay_url, created_at, paid_at, applied_at, refunded_at
`

type CreatePackagePaymentParams struct {
	Provider   string
	Payload    string
	TgID       int64
	UserID     sql.NullInt64
	PackageID  sql.NullInt64
	TariffName string
	Amount     int64
	Currency   string
	CreatedAt  int64
}

func (q *Queries) CreatePackagePayment(ctx context.Context, arg CreatePackagePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPackagePayment,
		arg.Provider,
		arg.Payload,
		arg.TgID,
		arg.UserID,
		arg.PackageID,
		arg.TariffName,
		arg.Amount,
		arg.Currency,
		arg.CreatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Payload,
		&i.ExternalID,
		&i.TgID,
		&i.Kind,
		&i.UserID,
		&i.TariffID,
		&i.PackageID,
		&i.TariffName,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Error,
		&i.PayUrl,
		&i.CreatedAt,
		&i.PaidAt,
		&i.AppliedAt,
		&i.RefundedAt,
	)
	return i, err
}

const createTrafficGrant = `-- name: CreateTrafficGrant :one
INSERT INTO traffic_grants (user_id, pool_id, bytes, remaining, lifetime, expires_at, source, payment_id, package_id, note, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, pool_id, bytes, remaining, lifetime, expires_at, source, payment_id, package_id, note, created_at
`

type CreateTrafficGrantParams struct {
	UserID    int64
	PoolID    sql.NullInt64
	Bytes     int64
	Remaining int64
	Lifetime  string
	ExpiresAt sql.NullInt64
	Source    string
	PaymentID sql.NullInt64
	PackageID sql.NullInt64
	Note      string
	CreatedAt int64
}

func (q *Queries) CreateTrafficGrant(ctx context.Context, arg CreateTrafficGrantParams) (TrafficGrant, error) {
	row := q.db.QueryRowContext(ctx, createTrafficGrant,
		arg.UserID,
		arg.PoolID,
		arg.Bytes,
		arg.Remaining,
		arg.Lifetime,
		arg.ExpiresAt,
		arg.Source,
		arg.PaymentID,
		arg.PackageID,
		arg.Note,
		arg.CreatedAt,
	)
	var i TrafficGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PoolID,
		&i.Bytes,
		&i.Remaining,
		&i.Lifetime,
		&i.ExpiresAt,
		&i.Source,
		&i.PaymentID,
		&i.PackageID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createTrafficPackage = `-- name: CreateTrafficPackage :one
INSERT INTO traffic_packages (name, bytes, pool_id, lifetime, days, price_stars, price_rub, on_sale, sort, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, bytes, pool_id, lifetime, days, price_stars, price_rub, on_sale, sort, archived, created_at
`

type CreateTrafficPackageParams struct {
	Name       string
	Bytes      int64
	PoolID     sql.NullInt64
	Lifetime   string
	Days       int64
	PriceStars sql.NullInt64
	PriceRub   sql.NullInt64
	OnSale     int64
	Sort       int64
	CreatedAt  int64
}

func (q *Queries) CreateTrafficPackage(ctx context.Context, arg CreateTrafficPackageParams) (TrafficPackage, error) {
	row := q.db.QueryRowContext(ctx, createTrafficPackage,
		arg.Name,
		arg.Bytes,
		arg.PoolID,
		arg.Lifetime,
		arg.Days,
		arg.PriceStars,
		arg.PriceRub,
		arg.OnSale,
		arg.Sort,
		arg.CreatedAt,
	)
	var i TrafficPackage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bytes,
		&i.PoolID,
		&i.Lifetime,
		&i.Days,
		&i.PriceStars,
		&i.PriceRub,
		&i.OnSale,
		&i.Sort,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const endPeriodGrants = `-- name: EndPeriodGrants :exec
UPDATE traffic_grants SET expires_at = CAST(?1 AS INTEGER)
WHERE user_id = ?2 AND lifetime = 'period' AND remaining > 0
  AND (expires_at IS NULL OR expires_at > CAST(?1 AS INTEGER))
`

type EndPeriodGrantsParams struct {
	Now    int64
	UserID int64
}

// A new traffic period ends the grants that last one period.
func (q *Queries) EndPeriodGrants(ctx context.Context, arg EndPeriodGrantsParams) error {
	_, err := q.db.ExecContext(ctx, endPeriodGrants, arg.Now, arg.UserID)
	return err
}

const findOpenPackagePayment = `-- name: FindOpenPackagePayment :one
SELECT id, provider, payload, external_id, tg_id, kind, user_id, tariff_id, package_id, tariff_name, amount, currency, status, error, pay_url, created_at, paid_at, applied_at, refunded_at FROM payments
WHERE tg_id = ? AND package_id = ? AND provider = ? AND kind = 'package' AND user_id = ?
  AND status = 'pending' AND pay_url <> '' AND created_at > ?5
ORDER BY id DESC LIMIT 1
`

type FindOpenPackagePaymentParams struct {
	TgID      int64
	PackageID sql.NullInt64
	Provider  string
	UserID    sql.NullInt64
	Since     int64
}

func (q *Queries) FindOpenPackagePayment(ctx context.Context, arg FindOpenPackagePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, findOpenPackagePayment,
		arg.TgID,
		arg.PackageID,
		arg.Provider,
		arg.UserID,
		arg.Since,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Payload,
		&i.ExternalID,
		&i.TgID,
		&i.Kind,
		&i.UserID,
		&i.TariffID,
		&i.PackageID,
		&i.TariffName,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Error,
		&i.PayUrl,
		&i.CreatedAt,
		&i.PaidAt,
		&i.AppliedAt,
		&i.RefundedAt,
	)
	return i, err
}

const getTrafficPackage = `-- name: GetTrafficPackage :one
SELECT id, name, bytes, pool_id, lifetime, days, price_stars, price_rub, on_sale, sort, archived, created_at FROM traffic_packages WHERE id = ?
`

func (q *Queries) GetTrafficPackage(ctx context.Context, id int64) (TrafficPackage, error) {
	row := q.db.QueryRowContext(ctx, getTrafficPackage, id)
	var i TrafficPackage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bytes,
		&i.PoolID,
		&i.Lifetime,
		&i.Days,
		&i.PriceStars,
		&i.PriceRub,
		&i.OnSale,
		&i.Sort,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPool = `-- name: GetUserPool :one
SELECT user_id, pool_id, traffic_limit, used_up, used_down FROM user_pools WHERE user_id = ? AND pool_id = ?
`

type GetUserPoolParams struct {
	UserID int64
	PoolID int64
}

func (q *Queries) GetUserPool(ctx context.Context, arg GetUserPoolParams) (UserPool, error) {
	row := q.db.QueryRowContext(ctx, getUserPool, arg.UserID, arg.PoolID)
	var i UserPool
	err := row.Scan(
		&i.UserID,
		&i.PoolID,
		&i.TrafficLimit,
		&i.UsedUp,
		&i.UsedDown,
	)
	return i, err
}

const listAllTrafficPackages = `-- name: ListAllTrafficPackages :many
SELECT id, name, bytes, pool_id, lifetime, days, price_stars, price_rub, on_sale, sort, archived, created_at FROM traffic_packages ORDER BY id
`

// Archived ones too: grants and payments keep naming them.
func (q *Queries) ListAllTrafficPackages(ctx context.Context) ([]TrafficPackage, error) {
	rows, err := q.db.QueryContext(ctx, listAllTrafficPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficPackage{}
	for rows.Next() {
		var i TrafficPackage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bytes,
			&i.PoolID,
			&i.Lifetime,
			&i.Days,
			&i.PriceStars,
			&i.PriceRub,
			&i.OnSale,
			&i.Sort,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpendableGrants = `-- name: ListSpendableGrants :many
SELECT id, user_id, pool_id, bytes, remaining, lifetime, expires_at, source, payment_id, package_id, note, created_at FROM traffic_grants
WHERE user_id = ?1 AND pool_id IS ?2 AND remaining > 0
  AND (expires_at IS NULL OR expires_at > CAST(?3 AS INTEGER))
ORDER BY expires_at IS NULL, expires_at, created_at, id
`

type ListSpendableGrantsParams struct {
	UserID int64
	PoolID sql.NullInt64
	Now    int64
}

// The order traffic past the base quota is taken in: the soonest to expire first, then
// the oldest. Expired and used-up grants are left out.
func (q *Queries) ListSpendableGrants(ctx context.Context, arg ListSpendableGrantsParams) ([]TrafficGrant, error) {
	rows, err := q.db.QueryContext(ctx, listSpendableGrants, arg.UserID, arg.PoolID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficGrant{}
	for rows.Next() {
		var i TrafficGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PoolID,
			&i.Bytes,
			&i.Remaining,
			&i.Lifetime,
			&i.ExpiresAt,
			&i.Source,
			&i.PaymentID,
			&i.PackageID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrafficPackages = `-- name: ListTrafficPackages :many
SELECT id, name, bytes, pool_id, lifetime, days, price_stars, price_rub, on_sale, sort, archived, created_at FROM traffic_packages WHERE archived = 0 ORDER BY sort, id
`

func (q *Queries) ListTrafficPackages(ctx context.Context) ([]TrafficPackage, error) {
	rows, err := q.db.QueryContext(ctx, listTrafficPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficPackage{}
	for rows.Next() {
		var i TrafficPackage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bytes,
			&i.PoolID,
			&i.Lifetime,
			&i.Days,
			&i.PriceStars,
			&i.PriceRub,
			&i.OnSale,
			&i.Sort,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrafficPackagesOnSale = `-- name: ListTrafficPackagesOnSale :many
SELECT id, name, bytes, pool_id, lifetime, days, price_stars, price_rub, on_sale, sort, archived, created_at FROM traffic_packages WHERE archived = 0 AND on_sale = 1 ORDER BY sort, id
`

func (q *Queries) ListTrafficPackagesOnSale(ctx context.Context) ([]TrafficPackage, error) {
	rows, err := q.db.QueryContext(ctx, listTrafficPackagesOnSale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficPackage{}
	for rows.Next() {
		var i TrafficPackage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bytes,
			&i.PoolID,
			&i.Lifetime,
			&i.Days,
			&i.PriceStars,
			&i.PriceRub,
			&i.OnSale,
			&i.Sort,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGrants = `-- name: ListUserGrants :many
SELECT id, user_id, pool_id, bytes, remaining, lifetime, expires_at, source, payment_id, package_id, note, created_at FROM traffic_grants WHERE user_id = ? ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListUserGrants(ctx context.Context, userID int64) ([]TrafficGrant, error) {
	rows, err := q.db.QueryContext(ctx, listUserGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficGrant{}
	for rows.Next() {
		var i TrafficGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PoolID,
			&i.Bytes,
			&i.Remaining,
			&i.Lifetime,
			&i.ExpiresAt,
			&i.Source,
			&i.PaymentID,
			&i.PackageID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendGrant = `-- name: SpendGrant :exec
UPDATE traffic_grants SET remaining = remaining - ?1 WHERE id = ?2
`

type SpendGrantParams struct {
	Spent int64
	ID    int64
}

func (q *Queries) SpendGrant(ctx context.Context, arg SpendGrantParams) error {
	_, err := q.db.ExecContext(ctx, spendGrant, arg.Spent, arg.ID)
	return err
}

const sumGrantsLeft = `-- name: SumGrantsLeft :many
SELECT user_id, CAST(IFNULL(pool_id, 0) AS INTEGER) AS pool_id, CAST(SUM(remaining) AS INTEGER) AS left_bytes
FROM traffic_grants
WHERE remaining > 0 AND (expires_at IS NULL OR expires_at > CAST(?1 AS INTEGER))
GROUP BY user_id, IFNULL(pool_id, 0)
`

type SumGrantsLeftRow struct {
	UserID    int64
	PoolID    int64
	LeftBytes int64
}

// What is left of the active grants per user and target (pool 0: the main traffic).
func (q *Queries) SumGrantsLeft(ctx context.Context, now int64) ([]SumGrantsLeftRow, error) {
	rows, err := q.db.QueryContext(ctx, sumGrantsLeft, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumGrantsLeftRow{}
	for rows.Next() {
		var i SumGrantsLeftRow
		if err := rows.Scan(&i.UserID, &i.PoolID, &i.LeftBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUserGrantsLeft = `-- name: SumUserGrantsLeft :many
SELECT user_id, CAST(IFNULL(pool_id, 0) AS INTEGER) AS pool_id, CAST(SUM(remaining) AS INTEGER) AS left_bytes
FROM traffic_grants
WHERE user_id = ?1 AND remaining > 0 AND (expires_at IS NULL OR expires_at > CAST(?2 AS INTEGER))
GROUP BY user_id, IFNULL(pool_id, 0)
`

type SumUserGrantsLeftParams struct {
	UserID int64
	Now    int64
}

type SumUserGrantsLeftRow struct {
	UserID    int64
	PoolID    int64
	LeftBytes int64
}

func (q *Queries) SumUserGrantsLeft(ctx context.Context, arg SumUserGrantsLeftParams) ([]SumUserGrantsLeftRow, error) {
	rows, err := q.db.QueryContext(ctx, sumUserGrantsLeft, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumUserGrantsLeftRow{}
	for rows.Next() {
		var i SumUserGrantsLeftRow
		if err := rows.Scan(&i.UserID, &i.PoolID, &i.LeftBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrafficPackage = `-- name: UpdateTrafficPackage :one
UPDATE traffic_packages
SET name = ?, bytes = ?, pool_id = ?, lifetime = ?, days = ?, price_stars = ?, price_rub = ?, on_sale = ?, sort = ?
WHERE id = ? AND archived = 0
RETURNING id, name, bytes, pool_id, lifetime, days, price_stars, price_rub, on_sale, sort, archived, created_at
`

type UpdateTrafficPackageParams struct {
	Name       string
	Bytes      int64
	PoolID     sql.NullInt64
	Lifetime   string
	Days       int64
	PriceStars sql.NullInt64
	PriceRub   sql.NullInt64
	OnSale     int64
	Sort       int64
	ID         int64
}

func (q *Queries) UpdateTrafficPackage(ctx context.Context, arg UpdateTrafficPackageParams) (TrafficPackage, error) {
	row := q.db.QueryRowContext(ctx, updateTrafficPackage,
		arg.Name,
		arg.Bytes,
		arg.PoolID,
		arg.Lifetime,
		arg.Days,
		arg.PriceStars,
		arg.PriceRub,
		arg.OnSale,
		arg.Sort,
		arg.ID,
	)
	var i TrafficPackage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bytes,
		&i.PoolID,
		&i.Lifetime,
		&i.Days,
		&i.PriceStars,
		&i.PriceRub,
		&i.OnSale,
		&i.Sort,
		&i.Archived,
		&i.CreatedAt,
	)
	return i, err
}
