// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pools.sql

package db

import (
	"context"
	"database/sql"
)

const addTariffPool = `-- name: AddTariffPool :exec
INSERT INTO tariff_pools (tariff_id, pool_id, traffic_limit) VALUES (?, ?, ?)
`

type AddTariffPoolParams struct {
	TariffID     int64
	PoolID       int64
	TrafficLimit int64
}

func (q *Queries) AddTariffPool(ctx context.Context, arg AddTariffPoolParams) error {
	_, err := q.db.ExecContext(ctx, addTariffPool, arg.TariffID, arg.PoolID, arg.TrafficLimit)
	return err
}

const addUserPoolTraffic = `-- name: AddUserPoolTraffic :exec
INSERT INTO user_pools (user_id, pool_id, used_up, used_down) VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, pool_id) DO UPDATE SET used_up = used_up + excluded.used_up, used_down = used_down + excluded.used_down
`

type AddUserPoolTrafficParams struct {
	UserID   int64
	PoolID   int64
	UsedUp   int64
	UsedDown int64
}

func (q *Queries) AddUserPoolTraffic(ctx context.Context, arg AddUserPoolTrafficParams) error {
	_, err := q.db.ExecContext(ctx, addUserPoolTraffic,
		arg.UserID,
		arg.PoolID,
		arg.UsedUp,
		arg.UsedDown,
	)
	return err
}

const addUserTotalTraffic = `-- name: AddUserTotalTraffic :exec
UPDATE users SET total_up = total_up + ?1, total_down = total_down + ?2 WHERE id = ?3
`

type AddUserTotalTrafficParams struct {
	Up   int64
	Down int64
	ID   int64
}

// Pool traffic: the all-time totals take it, the main period's counters do not.
func (q *Queries) AddUserTotalTraffic(ctx context.Context, arg AddUserTotalTrafficParams) error {
	_, err := q.db.ExecContext(ctx, addUserTotalTraffic, arg.Up, arg.Down, arg.ID)
	return err
}

const clearTariffPools = `-- name: ClearTariffPools :exec
DELETE FROM tariff_pools WHERE tariff_id = ?
`

func (q *Queries) ClearTariffPools(ctx context.Context, tariffID int64) error {
	_, err := q.db.ExecContext(ctx, clearTariffPools, tariffID)
	return err
}

const clearUserPoolLimits = `-- name: ClearUserPoolLimits :exec
UPDATE user_pools SET traffic_limit = NULL WHERE user_id = ?
`

func (q *Queries) ClearUserPoolLimits(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, clearUserPoolLimits, userID)
	return err
}

const createTrafficPool = `-- name: CreateTrafficPool :one
INSERT INTO traffic_pools (name, created_at) VALUES (?, ?) RETURNING id, name, created_at
`

type CreateTrafficPoolParams struct {
	Name      string
	CreatedAt int64
}

func (q *Queries) CreateTrafficPool(ctx context.Context, arg CreateTrafficPoolParams) (TrafficPool, error) {
	row := q.db.QueryRowContext(ctx, createTrafficPool, arg.Name, arg.CreatedAt)
	var i TrafficPool
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteTrafficPool = `-- name: DeleteTrafficPool :execrows
DELETE FROM traffic_pools WHERE id = ?
`

func (q *Queries) DeleteTrafficPool(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrafficPool, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTrafficPool = `-- name: GetTrafficPool :one
SELECT id, name, created_at FROM traffic_pools WHERE id = ?
`

func (q *Queries) GetTrafficPool(ctx context.Context, id int64) (TrafficPool, error) {
	row := q.db.QueryRowContext(ctx, getTrafficPool, id)
	var i TrafficPool
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listAllTariffPools = `-- name: ListAllTariffPools :many
SELECT tariff_id, pool_id, traffic_limit FROM tariff_pools ORDER BY tariff_id, pool_id
`

func (q *Queries) ListAllTariffPools(ctx context.Context) ([]TariffPool, error) {
	rows, err := q.db.QueryContext(ctx, listAllTariffPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TariffPool{}
	for rows.Next() {
		var i TariffPool
		if err := rows.Scan(&i.TariffID, &i.PoolID, &i.TrafficLimit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUserPools = `-- name: ListAllUserPools :many
SELECT user_id, pool_id, traffic_limit, used_up, used_down FROM user_pools ORDER BY user_id, pool_id
`

func (q *Queries) ListAllUserPools(ctx context.Context) ([]UserPool, error) {
	rows, err := q.db.QueryContext(ctx, listAllUserPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPool{}
	for rows.Next() {
		var i UserPool
		if err := rows.Scan(
			&i.UserID,
			&i.PoolID,
			&i.TrafficLimit,
			&i.UsedUp,
			&i.UsedDown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTariffPools = `-- name: ListTariffPools :many
SELECT tariff_id, pool_id, traffic_limit FROM tariff_pools WHERE tariff_id = ? ORDER BY pool_id
`

func (q *Queries) ListTariffPools(ctx context.Context, tariffID int64) ([]TariffPool, error) {
	rows, err := q.db.QueryContext(ctx, listTariffPools, tariffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TariffPool{}
	for rows.Next() {
		var i TariffPool
		if err := rows.Scan(&i.TariffID, &i.PoolID, &i.TrafficLimit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrafficPools = `-- name: ListTrafficPools :many
SELECT id, name, created_at FROM traffic_pools ORDER BY name
`

func (q *Queries) ListTrafficPools(ctx context.Context) ([]TrafficPool, error) {
	rows, err := q.db.QueryContext(ctx, listTrafficPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficPool{}
	for rows.Next() {
		var i TrafficPool
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPools = `-- name: ListUserPools :many
SELECT user_id, pool_id, traffic_limit, used_up, used_down FROM user_pools WHERE user_id = ? ORDER BY pool_id
`

func (q *Queries) ListUserPools(ctx context.Context, userID int64) ([]UserPool, error) {
	rows, err := q.db.QueryContext(ctx, listUserPools, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPool{}
	for rows.Next() {
		var i UserPool
		if err := rows.Scan(
			&i.UserID,
			&i.PoolID,
			&i.TrafficLimit,
			&i.UsedUp,
			&i.UsedDown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const poolUsage = `-- name: PoolUsage :one
SELECT
  (SELECT COUNT(*) FROM traffic_grants g
    WHERE g.pool_id = ?1 AND g.remaining > 0 AND (g.expires_at IS NULL OR g.expires_at > CAST(?2 AS INTEGER))) AS grants,
  (SELECT COUNT(*) FROM traffic_packages k WHERE k.pool_id = ?1 AND k.archived = 0) AS packages,
  (SELECT COUNT(*) FROM payments p JOIN traffic_packages k ON k.id = p.package_id
    WHERE k.pool_id = ?1 AND p.status IN ('pending', 'paid')) AS payments
`

type PoolUsageParams struct {
	PoolID sql.NullInt64
	Now    int64
}

type PoolUsageRow struct {
	Grants   int64
	Packages int64
	Payments int64
}

// What a pool still holds that deleting it would destroy (the cascade takes grants and
// packages with it, and a paid invoice of a package loses the package): traffic users
// paid for and have left, packages of the catalog, invoices not closed yet.
func (q *Queries) PoolUsage(ctx context.Context, arg PoolUsageParams) (PoolUsageRow, error) {
	row := q.db.QueryRowContext(ctx, poolUsage, arg.PoolID, arg.Now)
	var i PoolUsageRow
	err := row.Scan(&i.Grants, &i.Packages, &i.Payments)
	return i, err
}

const renameTrafficPool = `-- name: RenameTrafficPool :execrows
UPDATE traffic_pools SET name = ? WHERE id = ?
`

type RenameTrafficPoolParams struct {
	Name string
	ID   int64
}

func (q *Queries) RenameTrafficPool(ctx context.Context, arg RenameTrafficPoolParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameTrafficPool, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetUserPools = `-- name: ResetUserPools :exec
UPDATE user_pools SET used_up = 0, used_down = 0 WHERE user_id = ?
`

// Pools reset with the main traffic: a new period, a renewal, the admin's reset.
func (q *Queries) ResetUserPools(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, resetUserPools, userID)
	return err
}

const setInboundPool = `-- name: SetInboundPool :exec
UPDATE inbounds SET pool_id = ? WHERE id = ?
`

type SetInboundPoolParams struct {
	PoolID sql.NullInt64
	ID     int64
}

func (q *Queries) SetInboundPool(ctx context.Context, arg SetInboundPoolParams) error {
	_, err := q.db.ExecContext(ctx, setInboundPool, arg.PoolID, arg.ID)
	return err
}

const setUserPoolLimit = `-- name: SetUserPoolLimit :exec
INSERT INTO user_pools (user_id, pool_id, traffic_limit) VALUES (?, ?, ?)
ON CONFLICT (user_id, pool_id) DO UPDATE SET traffic_limit = excluded.traffic_limit
`

type SetUserPoolLimitParams struct {
	UserID       int64
	PoolID       int64
	TrafficLimit sql.NullInt64
}

func (q *Queries) SetUserPoolLimit(ctx context.Context, arg SetUserPoolLimitParams) error {
	_, err := q.db.ExecContext(ctx, setUserPoolLimit, arg.UserID, arg.PoolID, arg.TrafficLimit)
	return err
}
