// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warp.sql

package db

import (
	"context"
)

const deleteNodeWarp = `-- name: DeleteNodeWarp :execrows
DELETE FROM node_warp WHERE node_id = ?
`

func (q *Queries) DeleteNodeWarp(ctx context.Context, nodeID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNodeWarp, nodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNodeWarp = `-- name: GetNodeWarp :one
SELECT node_id, enabled, source, private_key, peer_public_key, endpoint, ipv4, ipv6, reserved, mtu, account_id, account_token, plus, routes, created_at, updated_at FROM node_warp WHERE node_id = ?
`

func (q *Queries) GetNodeWarp(ctx context.Context, nodeID int64) (NodeWarp, error) {
	row := q.db.QueryRowContext(ctx, getNodeWarp, nodeID)
	var i NodeWarp
	err := row.Scan(
		&i.NodeID,
		&i.Enabled,
		&i.Source,
		&i.PrivateKey,
		&i.PeerPublicKey,
		&i.Endpoint,
		&i.Ipv4,
		&i.Ipv6,
		&i.Reserved,
		&i.Mtu,
		&i.AccountID,
		&i.AccountToken,
		&i.Plus,
		&i.Routes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveNodeWarp = `-- name: SaveNodeWarp :exec
INSERT INTO node_warp (node_id, enabled, source, private_key, peer_public_key, endpoint, ipv4, ipv6, reserved, mtu,
  account_id, account_token, plus, routes, created_at, updated_at)
VALUES (?, 1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (node_id) DO UPDATE SET enabled = 1, source = excluded.source, private_key = excluded.private_key,
  peer_public_key = excluded.peer_public_key, endpoint = excluded.endpoint, ipv4 = excluded.ipv4, ipv6 = excluded.ipv6,
  reserved = excluded.reserved, mtu = excluded.mtu, account_id = excluded.account_id, account_token = excluded.account_token,
  plus = excluded.plus, updated_at = excluded.updated_at
`

type SaveNodeWarpParams struct {
	NodeID        int64
	Source        string
	PrivateKey    string
	PeerPublicKey string
	Endpoint      string
	Ipv4          string
	Ipv6          string
	Reserved      string
	Mtu           int64
	AccountID     string
	AccountToken  string
	Plus          int64
	Routes        string
	CreatedAt     int64
	UpdatedAt     int64
}

func (q *Queries) SaveNodeWarp(ctx context.Context, arg SaveNodeWarpParams) error {
	_, err := q.db.ExecContext(ctx, saveNodeWarp,
		arg.NodeID,
		arg.Source,
		arg.PrivateKey,
		arg.PeerPublicKey,
		arg.Endpoint,
		arg.Ipv4,
		arg.Ipv6,
		arg.Reserved,
		arg.Mtu,
		arg.AccountID,
		arg.AccountToken,
		arg.Plus,
		arg.Routes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const setInboundOutbound = `-- name: SetInboundOutbound :exec
UPDATE inbounds SET outbound = ? WHERE id = ?
`

type SetInboundOutboundParams struct {
	Outbound string
	ID       int64
}

func (q *Queries) SetInboundOutbound(ctx context.Context, arg SetInboundOutboundParams) error {
	_, err := q.db.ExecContext(ctx, setInboundOutbound, arg.Outbound, arg.ID)
	return err
}

const setNodeWarpOptions = `-- name: SetNodeWarpOptions :exec
UPDATE node_warp SET enabled = ?, routes = ?, updated_at = ? WHERE node_id = ?
`

type SetNodeWarpOptionsParams struct {
	Enabled   int64
	Routes    string
	UpdatedAt int64
	NodeID    int64
}

func (q *Queries) SetNodeWarpOptions(ctx context.Context, arg SetNodeWarpOptionsParams) error {
	_, err := q.db.ExecContext(ctx, setNodeWarpOptions,
		arg.Enabled,
		arg.Routes,
		arg.UpdatedAt,
		arg.NodeID,
	)
	return err
}

const setNodeWarpPlus = `-- name: SetNodeWarpPlus :exec
UPDATE node_warp SET plus = ?, updated_at = ? WHERE node_id = ?
`

type SetNodeWarpPlusParams struct {
	Plus      int64
	UpdatedAt int64
	NodeID    int64
}

func (q *Queries) SetNodeWarpPlus(ctx context.Context, arg SetNodeWarpPlusParams) error {
	_, err := q.db.ExecContext(ctx, setNodeWarpPlus, arg.Plus, arg.UpdatedAt, arg.NodeID)
	return err
}
